### ISSUE TITLE
Support middleware inheritance in routes

### ISSUE THREAD

**Issue by h2non** [vinxi/router#7]
Basically, as part of the hierarchical middleware layer feature, we can now extend that capability to other packages. In particular, it becomes really useful in routes, where the route is by itself is a middleware capable interface.

So the main idea behind this is a simple as allow that routes can have a parent layer, implicitly providing cross-layer binding which is perfect when handling `panic`/`errors`, since the parent generic layer will be triggered to handle it properly, having a cross-layer error handling. Also, it could be extended in a future when new middleware phases will be used, even defined by developers.

@groyoh would you mind taking this task? I think you will find it interesting. Also, any idea to take more advantages would be great.

**Comment by h2non** [comment]
Just to point out that in order to support this properly it will also require changes in `vinxi/vinxi`.

**Comment by groyoh** [comment]
Yeah, sounds good to me!

**Comment by h2non** [comment]
Already supported via: https://github.com/vinxi/router/commit/e63da3cd5c60d6ac2846cc51344f0300f8cbece3

PS: I've to support this to do some real testing from `vinxi` package. Further improvements are welcome.
